export const USERNAME_STORE_KEY = "PUX_BLD_USERNAME";
export const PASSWORD_STORE_KEY = "PUX_BLD_PASSWORD";
export const ACCESS_TOKEN_STORE_KEY = "PUX_BLD_ACCESS_TOKEN";
export const FIXED_QUIZ_STORE_KEY = "PUX_FIXED_QUIZ";
export const FLASH_CARD_FILTER_STORE_KEY = "PUX_BLD_FLASH_CARD_FILTER";
export const OPTIONS_LOCAL_STORAGE_KEY = "PUX_BLD_OPTIONS";
export const QUIZ_OLDEST_STORE_KEY = "PUX_BLD_QUIZ_OLDEST";
export const QUIZ_MEMO_CONFIDENCE_STORE_KEY = "PUX_BLD_QUIZ_MEMO_CONFIDENCE";
export const QUIZ_COMM_CONFIDENCE_STORE_KEY = "PUX_BLD_QUIZ_COMM_CONFIDENCE";
export const QUIZ_RANDOM_STORE_KEY = "PUX_BLD_QUIZ_RANDOM";
export const DRILL_INFO_STORE_KEY = "PUX_BLD_DRILL_INFO";
export const DRILL_ITEMS_STORE_KEY = "PUX_BLD_DRILL_ITEMS";
export const CURRENT_QUIZ_LETTER_PAIRS_STORE_KEY = "PUX_BLD_CURRENT_QUIZ_LETTER_PAIRS";
export const CURRENT_QUIZ_AGE_STORE_KEY = "PUX_BLD_CURRENT_QUIZ_AGE";
export const CURRENT_QUIZ_TYPE_STORE_KEY = "PUX_BLD_CURRENT_QUIZ_TYPE";
export const OPTIONS_STORE_PREFIX = "PUX_OPTIONS";

export const SPEFFZ_UBL = ["a", "e", "r"];
export const SPEFFZ_UFR = ["c", "j", "m"];
export const SPEFFZ_SAME_PIECES = [
	SPEFFZ_UBL,
	["b", "n", "q"],
	SPEFFZ_UFR,
	["d", "f", "i"],
	["g", "l", "u"],
	["h", "s", "x"],
	["k", "p", "v"],
	["o", "t", "w"]
];
