export const USERNAME_STORE_KEY = "PUX_BLD_USERNAME";
export const PASSWORD_STORE_KEY = "PUX_BLD_PASSWORD";
export const ACCESS_TOKEN_STORE_KEY = "PUX_BLD_ACCESS_TOKEN";
export const FLASH_CARD_FILTER_STORE_KEY = "PUX_BLD_FLASH_CARD_FILTER";
