services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:27945"
    volumes:
      - ./volumes/user-images:/user-images
      - ./volumes/user-data:/user-data
